version: "3.8"

services:
  mongodb:
    image: mongo:7
    ports:
      - 27017:27017
    networks:
      - network_public
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb_data:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1m0chatm0ng0db
      - PUID=1000
      - PGID=1000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 6144M

volumes:
  mongodb_data:
    external: true
  mongodb_configdb_data:
    external: true

networks:
  network_public:
    external: true